import type { PresentationStage } from '../../presentation/presentationTypes';

export const collapseStages: PresentationStage[] = [
  {
    id: 'collapse-cliff',
    order: 1,
    title: '陡坡危岩',
    description: '山体陡，岩体突出，坡脚区域已经存在潜在危险。',
    learningObjective: '理解崩塌常发生在陡坡、悬崖和道路边坡。',
    narration: '崩塌不同于滑坡，它往往是岩土体突然脱离母体向下坠落。',
    riskTip: '坡脚和道路边缘不能长时间停留。',
    actionAdvice: '观察陡坡环境，提前远离落石方向。',
    scene: { stageKey: 'cliff_rock', focus: '陡坡危岩', layers: ['cliff', 'rock'] },
    stateEffects: [{ key: 'warning', intensity: 0.35, description: '危岩区域提示。' }],
    timelineEvents: [{ key: 'danger_zone_show', at: 0.35, description: '坡脚危险区标记。' }],
    interaction: { type: 'none' },
    knowledge: '陡坡上突出的不稳定岩体，是崩塌风险的重要来源。',
  },
  {
    id: 'collapse-crack',
    order: 2,
    title: '岩体裂缝',
    description: '危岩上出现岩体新裂缝，岩体完整性下降。',
    learningObjective: '识别岩体新裂缝是崩塌前兆。',
    narration: '新的裂缝说明岩体可能正在松动。',
    riskTip: '岩体新裂缝出现后，崩塌风险上升。',
    actionAdvice: '不要靠近裂缝岩体观察。',
    scene: { stageKey: 'rock_crack', focus: '岩体裂缝', layers: ['cliff', 'crack'] },
    stateEffects: [{ key: 'crack', intensity: 0.55, description: '裂缝扩大。' }],
    timelineEvents: [{ key: 'rock_crack', at: 0.55, description: '裂缝沿岩体扩展。' }],
    interaction: { type: 'none' },
    knowledge: '岩体裂缝可能是大块岩石脱落前的信号。',
  },
  {
    id: 'collapse-small-rockfall',
    order: 3,
    title: '小石块掉落',
    description: '小石块先从坡面掉落，提示岩体正在松动。',
    learningObjective: '理解小石块掉落不是小事，而是危险信号。',
    narration: '如果小石块不断掉下来，应立即离开坡脚。',
    riskTip: '小石块掉落后，可能跟着发生更大规模崩落。',
    actionAdvice: '赶快躲开，不要在陡坡下面停留。',
    scene: { stageKey: 'small_rockfall', focus: '小石块掉落', layers: ['cliff', 'falling_rocks'] },
    stateEffects: [{ key: 'warning', intensity: 0.72, description: '落石预警。' }],
    timelineEvents: [{ key: 'rockfall', at: 0.4, description: '小石块滚落。' }],
    interaction: { type: 'none' },
    knowledge: '前缘时有小石块不断掉下来，是崩塌前兆之一。',
  },
  {
    id: 'collapse-sound',
    order: 4,
    title: '岩石摩擦声',
    description: '岩石出现撕裂、摩擦声，危险进一步加剧。',
    learningObjective: '理解异常声音也可能是崩塌前兆。',
    narration: '听到岩石摩擦声，说明岩体可能正在失稳。',
    riskTip: '异常声音出现时，不要围观。',
    actionAdvice: '快速远离坡脚和道路边缘。',
    scene: { stageKey: 'rock_sound', focus: '声音提示', layers: ['sound_wave', 'warning'] },
    stateEffects: [{ key: 'warning', intensity: 0.82, description: '声音警示增强。' }],
    timelineEvents: [{ key: 'sound_warning', at: 0.5, description: '出现摩擦声提示。' }],
    interaction: { type: 'none' },
    knowledge: '岩石摩擦声是需要立即远离的信号。',
  },
  {
    id: 'collapse-fall',
    order: 5,
    title: '大块岩体崩落',
    description: '大块岩体快速滚落到坡脚。',
    learningObjective: '认识崩塌速度极快，往往来不及反应。',
    narration: '崩塌发生时，岩体会迅速坠落、滚动并堆积在坡脚。',
    riskTip: '坡脚是最危险区域。',
    actionAdvice: '不要进入落石路径。',
    scene: { stageKey: 'collapse_fall', focus: '岩体快速崩落', layers: ['falling_mass', 'dust'] },
    stateEffects: [{ key: 'warning', intensity: 1, description: '大块岩体崩落。' }],
    timelineEvents: [{ key: 'rockfall', at: 0.32, description: '大块岩体滚落。' }],
    interaction: { type: 'none' },
    knowledge: '崩塌速度极快，提前识别前兆比现场反应更重要。',
  },
  {
    id: 'collapse-danger',
    order: 6,
    title: '坡脚危险区',
    description: '坡脚、陡坡下方、道路边缘变红。',
    learningObjective: '明确崩塌主要危险范围。',
    narration: '陡坡下方和道路边缘是落石容易影响的位置。',
    riskTip: '危险区域不能停留、不能围观。',
    actionAdvice: '绕开坡脚，远离陡坡。',
    scene: { stageKey: 'collapse_danger', focus: '坡脚危险区', layers: ['danger_zone'] },
    stateEffects: [{ key: 'warning', intensity: 1, description: '危险区高亮。' }],
    timelineEvents: [{ key: 'danger_zone_show', at: 0.3, description: '危险区出现。' }],
    interaction: { type: 'none' },
    knowledge: '崩塌避险不是跑得快，而是不要站在危险区。',
  },
  {
    id: 'collapse-escape',
    order: 7,
    title: '正确避险',
    description: '离开坡脚，不停留，不围观，不靠近观察。',
    learningObjective: '掌握崩塌远离陡坡的避险原则。',
    narration: '看到掉石头，赶快躲开，不要在陡坡下面停留。',
    riskTip: '返回观看或拍照会重新进入危险区。',
    actionAdvice: '远离陡坡，通知他人，听从转移。',
    scene: { stageKey: 'collapse_escape', focus: '安全撤离方向', layers: ['safe_route'] },
    stateEffects: [{ key: 'safe_route', intensity: 1, description: '安全撤离方向。' }],
    timelineEvents: [{ key: 'high_route_show', at: 0.4, description: '安全方向出现。' }],
    interaction: { type: 'none' },
    knowledge: '口诀：看到掉石头，赶快躲开！',
  },
];
