import type { PresentationStage } from '../../presentation/presentationTypes';

export const debrisFlowStages: PresentationStage[] = [
  {
    id: 'debris-upstream-rain',
    order: 1,
    title: '上游暴雨',
    description: '山谷上方出现暴雨，水流开始增加。',
    learningObjective: '理解泥石流常与山区暴雨有关。',
    narration: '突降大暴雨会让沟谷汇水速度迅速增加。',
    riskTip: '上游暴雨也会影响下游沟口。',
    actionAdvice: '暴雨时不要进入沟谷。',
    scene: { stageKey: 'upstream_rain', focus: '上游暴雨', layers: ['rain', 'valley'] },
    stateEffects: [{ key: 'rain', intensity: 0.55, description: '上游暴雨增强。' }],
    timelineEvents: [{ key: 'rain_upstream', at: 0.35, description: '暴雨增强。' }],
    interaction: { type: 'none' },
    knowledge: '泥石流通常需要水流、松散土石和沟谷地形共同作用。',
  },
  {
    id: 'debris-valley-collect',
    order: 2,
    title: '沟谷汇水',
    description: '雨水向沟谷集中，沟道水量增加。',
    learningObjective: '理解为什么泥石流必须关注沟谷。',
    narration: '沟谷像通道，会把山坡上的水集中起来。',
    riskTip: '沟谷水量快速变化要警惕。',
    actionAdvice: '离开沟谷和沟口。',
    scene: { stageKey: 'valley_collect', focus: '沟谷汇水', layers: ['water_path'] },
    stateEffects: [{ key: 'water_penetration', intensity: 0.62, description: '沟谷汇水。' }],
    timelineEvents: [{ key: 'water_collect', at: 0.5, description: '水流向沟谷汇集。' }],
    interaction: { type: 'none' },
    knowledge: '泥石流沿沟谷快速向下游运动。',
  },
  {
    id: 'debris-sediment',
    order: 3,
    title: '松散土石',
    description: '泥沙、石块开始被水流带动。',
    learningObjective: '理解泥石流不是普通洪水。',
    narration: '沟谷里的松散土石被水流卷入后，冲击力会明显增强。',
    riskTip: '土石被带动后，危险快速上升。',
    actionAdvice: '不要在沟谷中观察水流。',
    scene: { stageKey: 'sediment_move', focus: '泥沙石块运动', layers: ['sediment'] },
    stateEffects: [{ key: 'slide', intensity: 0.72, description: '土石运动。' }],
    timelineEvents: [{ key: 'sediment_move', at: 0.45, description: '土石开始移动。' }],
    interaction: { type: 'none' },
    knowledge: '泥石流是水、泥沙和石头一起高速冲下来。',
  },
  {
    id: 'debris-muddy-water',
    order: 4,
    title: '水变浑',
    description: '沟谷水突然变得浑浊，水位可能上涨或断流。',
    learningObjective: '识别沟水变浑是泥石流前兆。',
    narration: '清水突然变浑，说明上游可能有泥沙石块被带动。',
    riskTip: '水变浑不是普通现象。',
    actionAdvice: '立即远离沟谷。',
    scene: { stageKey: 'muddy_water', focus: '浑水前兆', layers: ['muddy_water'] },
    stateEffects: [{ key: 'warning', intensity: 0.82, description: '浑水预警。' }],
    timelineEvents: [{ key: 'muddy_water', at: 0.4, description: '水体变浑。' }],
    interaction: { type: 'none' },
    knowledge: '河流水突然上涨或突然断流，也可能是前兆。',
  },
  {
    id: 'debris-rumble',
    order: 5,
    title: '山谷轰鸣',
    description: '山谷出现类似火车轰鸣的声音提示。',
    learningObjective: '理解异常声音是需要马上行动的信号。',
    narration: '山谷里像火车一样的轰鸣声，可能代表泥石流正在靠近。',
    riskTip: '听到轰鸣声不能停留确认。',
    actionAdvice: '马上往沟谷两侧高处走。',
    scene: { stageKey: 'rumble_warning', focus: '山谷轰鸣', layers: ['sound_warning'] },
    stateEffects: [{ key: 'warning', intensity: 0.9, description: '声音预警。' }],
    timelineEvents: [{ key: 'rumble_warning', at: 0.5, description: '轰鸣声出现。' }],
    interaction: { type: 'none' },
    knowledge: '泥石流来得突然，不能等看清再行动。',
  },
  {
    id: 'debris-surge',
    order: 6,
    title: '泥水石块下冲',
    description: '泥、水、石头沿沟谷高速冲下。',
    learningObjective: '认识泥石流速度快、冲击强。',
    narration: '泥石流沿沟谷高速运动，桥下、沟口、低处都很危险。',
    riskTip: '顺沟跑会被追上，躲桥下也危险。',
    actionAdvice: '离开沟谷，向两侧高处逃。',
    scene: { stageKey: 'debris_surge', focus: '泥石流高速下冲', layers: ['surge'] },
    stateEffects: [{ key: 'warning', intensity: 1, description: '高速冲刷。' }],
    timelineEvents: [{ key: 'debris_surge', at: 0.35, description: '泥石流下冲。' }],
    interaction: { type: 'none' },
    knowledge: '泥石流是全课程视觉冲击最强的风险场景。',
  },
  {
    id: 'debris-wrong',
    order: 7,
    title: '错误路线',
    description: '顺沟跑、躲桥下、回头拿东西全部标红。',
    learningObjective: '识别泥石流错误避险行为。',
    narration: '不要顺沟谷跑，也不要躲在桥下，更不能回头拿东西。',
    riskTip: '错误路线会进入泥石流运动路径。',
    actionAdvice: '立即改变方向，离开沟谷。',
    scene: { stageKey: 'wrong_escape', focus: '错误路线标红', layers: ['wrong_route'] },
    stateEffects: [{ key: 'warning', intensity: 1, description: '错误行为标红。' }],
    timelineEvents: [{ key: 'danger_zone_show', at: 0.4, description: '错误路线高亮。' }],
    interaction: { type: 'none' },
    knowledge: '错误避险往往比原地不动更危险。',
  },
  {
    id: 'debris-high',
    order: 8,
    title: '正确路线',
    description: '往沟谷两侧高处逃，绿色路线出现。',
    learningObjective: '掌握泥石流往高处逃的避险原则。',
    narration: '泥石流来了，往高处逃！不要顺着沟谷跑，也不要躲在桥下。',
    riskTip: '两侧高处更容易离开冲刷路径。',
    actionAdvice: '快速向沟谷两侧高处撤离。',
    scene: { stageKey: 'high_escape', focus: '两侧高处安全路线', layers: ['safe_route'] },
    stateEffects: [{ key: 'safe_route', intensity: 1, description: '高处安全路线。' }],
    timelineEvents: [{ key: 'high_route_show', at: 0.45, description: '绿色路线出现。' }],
    interaction: { type: 'none' },
    knowledge: '口诀：泥石流往高处逃。',
  },
];
