import type { PresentationStage } from '../../presentation/presentationTypes';

export const landslideStages: PresentationStage[] = [
  {
    id: 'landslide-rain',
    order: 1,
    title: '连续降雨',
    description: '天空变暗，雨滴增强，山坡表面逐渐湿润。',
    learningObjective: '理解连续降雨是滑坡风险累积的重要诱因。',
    narration: '连续降雨会让坡体含水量逐步升高，灾害风险不是突然出现的。',
    riskTip: '强降雨后，陡坡、坡脚和山区道路旁风险升高。',
    actionAdvice: '关注预警信息，减少进入山坡和沟谷附近活动。',
    scene: { stageKey: 'rain', focus: '天空变暗与雨量增强', layers: ['rain', 'terrain', 'wet_surface'] },
    stateEffects: [{ key: 'rain', intensity: 0.75, description: '雨量持续增强。' }],
    timelineEvents: [{ key: 'rain_intensify', at: 0.35, description: '雨幕增强，坡面湿润。' }],
    interaction: { type: 'none' },
    knowledge: '降雨会持续改变坡体含水状态，为后续失稳创造条件。',
  },
  {
    id: 'landslide-water-penetration',
    order: 2,
    title: '雨水进入坡体',
    description: '蓝色渗水路径进入坡体，土体颜色变深。',
    learningObjective: '理解水会降低坡体稳定性，而不只是形成表面水流。',
    narration: '雨水向下渗透，土体变重，内部抗剪强度降低。',
    riskTip: '坡体内部含水量升高后，外观看似平静也可能已经危险。',
    actionAdvice: '发现坡面渗水、浑水或排水异常时，应远离并上报。',
    scene: { stageKey: 'water_penetration', focus: '蓝色渗水路径进入坡体', layers: ['rain', 'water_penetration', 'soil'] },
    stateEffects: [{ key: 'water_penetration', intensity: 0.82, description: '水进入坡体。' }],
    timelineEvents: [{ key: 'water_penetrate', at: 0.55, description: '湿润范围向坡体内部扩大。' }],
    interaction: { type: 'none' },
    knowledge: '入渗会让坡体内部结构承受更大压力，稳定性开始下降。',
  },
  {
    id: 'landslide-soft-soil',
    order: 3,
    title: '土体变软',
    description: '坡体内部出现松动区域，风险等级继续上升。',
    learningObjective: '理解雨水会让土体强度下降，形成松软带。',
    narration: '土体变软后，坡体抵抗下滑的能力减弱，危险开始加速累积。',
    riskTip: '坡体变软常常发生在内部，不一定马上被肉眼看见。',
    actionAdvice: '连续降雨后不要在坡脚停留或靠近观察。',
    scene: { stageKey: 'soft_soil', focus: '坡体内部松动区域', layers: ['soft_soil', 'warning'] },
    stateEffects: [{ key: 'warning', intensity: 0.7, description: '土体强度下降。' }],
    timelineEvents: [{ key: 'water_penetrate', at: 0.7, description: '松动区域扩大。' }],
    interaction: { type: 'none' },
    knowledge: '土体变软是雨水影响坡体稳定性的关键过程。',
  },
  {
    id: 'landslide-weak-surface',
    order: 4,
    title: '软弱面高亮',
    description: '山体内部出现高亮滑动面，标注软弱面位置。',
    learningObjective: '理解滑坡常沿坡体内部相对软弱的位置发生。',
    narration: '当软弱面形成后，坡体可能沿这个面整体向下滑动。',
    riskTip: '软弱面意味着坡体已经具备明显失稳条件。',
    actionAdvice: '发现坡面持续渗水、鼓胀或错动，应尽快远离。',
    scene: { stageKey: 'weak_surface', focus: '软弱面与潜在滑动面', layers: ['weak_surface', 'annotation'] },
    stateEffects: [{ key: 'warning', intensity: 0.78, description: '软弱面形成。' }],
    timelineEvents: [{ key: 'slope_deform', at: 0.5, description: '潜在滑动面出现。' }],
    interaction: { type: 'none' },
    knowledge: '软弱面是判断坡体可能整体下滑的重要教学标注。',
  },
  {
    id: 'landslide-crack',
    order: 5,
    title: '裂缝变宽',
    description: '裂缝沿坡面扩展，树木歪斜，房屋出现裂缝。',
    learningObjective: '识别裂缝变宽、树木歪斜、房屋裂缝等滑坡前兆。',
    narration: '裂缝变宽说明坡体已经发生拉裂或局部位移，需要立即警惕。',
    riskTip: '裂缝变宽、树木歪斜、房屋裂缝、井水异常、动物异常都是前兆。',
    actionAdvice: '不要靠近查看裂缝，应撤离到安全区域并报告。',
    scene: { stageKey: 'crack', focus: '裂缝、树木与房屋异常', layers: ['terrain', 'crack', 'warning'] },
    stateEffects: [{ key: 'crack', intensity: 0.9, description: '裂缝扩大，坡体正在失稳。' }],
    timelineEvents: [{ key: 'crack_appear', at: 0.65, description: '裂缝扩大并出现分支。' }],
    interaction: {
      type: 'choice',
      prompt: '看到坡面裂缝扩大时应怎么做？',
      options: [
        { id: 'close_check', label: '靠近拍照观察', isCorrect: false, feedback: '靠近裂缝会进入危险区域。' },
        { id: 'leave_report', label: '远离并报告', isCorrect: true, feedback: '远离危险区并报告是更安全的选择。' },
      ],
    },
    knowledge: '裂缝不是普通地面纹理，而是坡体变形的重要可见证据。',
  },
  {
    id: 'landslide-slide',
    order: 6,
    title: '坡体下滑',
    description: '滑动区整体下移，红色危险区和下滑方向箭头出现。',
    learningObjective: '理解滑坡运动方向及其危险范围。',
    narration: '滑坡体会顺坡向下运动，坡脚和运动路径最危险。',
    riskTip: '不要沿滑坡下方、沟谷或道路低处撤离。',
    actionAdvice: '迅速判断滑动方向，向两侧稳定区域移动。',
    scene: { stageKey: 'slide', focus: '坡体下滑与危险区', layers: ['slide_mass', 'danger_zone', 'direction_arrow'] },
    stateEffects: [{ key: 'slide', intensity: 1, description: '坡体明显下滑。' }],
    timelineEvents: [{ key: 'mass_slide', at: 0.7, description: '危险区域覆盖坡脚。' }],
    interaction: { type: 'none' },
    knowledge: '滑坡方向决定主要危险范围，正确避险必须避开运动路径。',
  },
  {
    id: 'landslide-escape',
    order: 7,
    title: '避险路线',
    description: '红色错误路线显示顺坡向下跑，绿色正确路线显示向两侧跑。',
    learningObjective: '掌握滑坡来临时向两侧跑的避险原则。',
    narration: '滑坡来了，不要顺坡向下跑，也不要向滑坡体正前方跑，应向两侧撤离。',
    riskTip: '顺着滑坡方向逃生会进入滑动体和堆积区。',
    actionAdvice: '沿滑坡运动方向的两侧快速撤离，远离坡脚和沟谷。',
    scene: { stageKey: 'escape', focus: '错误路线与正确路线', layers: ['danger_arrow', 'safe_routes', 'escape_markers'] },
    stateEffects: [{ key: 'safe_route', intensity: 1, description: '正确撤离路线高亮。' }],
    timelineEvents: [{ key: 'escape_route_show', at: 0.55, description: '两侧安全路线出现。' }],
    interaction: {
      type: 'choice',
      prompt: '滑坡已经发生时，应选择哪种撤离方向？',
      options: [
        { id: 'downhill', label: '顺坡向下跑', isCorrect: false, feedback: '顺坡向下会进入滑坡运动路径。' },
        { id: 'sideways', label: '向两侧跑', isCorrect: true, feedback: '向两侧撤离可以尽快离开滑坡运动路径。' },
      ],
    },
    knowledge: '避险动作必须和滑坡运动方向相反思考，核心是离开滑动路径。',
  },
];
